// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.1.0.0
//      SpecFlow Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace AKCTests.SpecFlow
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.1.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("parsing_entry")]
    public partial class Parsing_EntryFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "parsing_entry.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "parsing_entry", "\tIn order to have useful information\r\n\tAs a user\r\n\tI want to parse an entry", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 6
#line hidden
#line 7
 testRunner.Given("a text to parse", @"WHY CAN’T WE FALL ASLEEP?  (newyorker.com)
- Your Highlight on Location 24-25 | Added on Saturday, July 18, 2015 8:54:04 AM

If you’re “out of phase” from typical bedtimes due to circadian disruption, for example, your melatonin levels are off:
==========
﻿Freethinkers: A History of American Secularism (Jacoby, Susan)
- Your Highlight on page 3 | Location 90-91 | Added on Wednesday, August 12, 2015 8:54:41 PM

Bush’s very presence in the pulpit attested powerfully to the erosion of America’s secularist tradition;
==========
Freethinkers: A History of American Secularism (Jacoby, Susan)
- Your Highlight on page 33 | Location 557-560 | Added on Wednesday, August 12, 2015 10:03:09 PM

The absurdity of the claim that the framers somehow overlooked, or misunderstood, the political and religious implications of leaving God out of the nation’s founding document is borne out not only by Washington’s matter-of-fact assumption of the distinction between religious affiliation and citizenship but by the intensity and clarity of the public debate that preceded ratification of the Constitution.
==========", ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 25
 testRunner.When("I parse it", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Delimiters")]
        public virtual void Delimiters()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Delimiters", ((string[])(null)));
#line 27
this.ScenarioSetup(scenarioInfo);
#line 6
this.FeatureBackground();
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("number of entries")]
        public virtual void NumberOfEntries()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("number of entries", ((string[])(null)));
#line 28
this.ScenarioSetup(scenarioInfo);
#line 6
this.FeatureBackground();
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("catch the name of the book")]
        public virtual void CatchTheNameOfTheBook()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("catch the name of the book", ((string[])(null)));
#line 29
this.ScenarioSetup(scenarioInfo);
#line 6
this.FeatureBackground();
#line hidden
#line 30
 testRunner.Given("a text to parse", @"WHY CAN’T WE FALL ASLEEP?  (newyorker.com)
- Your Highlight on Location 24-25 | Added on Saturday, July 18, 2015 8:54:04 AM

If you’re “out of phase” from typical bedtimes due to circadian disruption, for example, your melatonin levels are off:
==========", ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 38
 testRunner.When("I parse it", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 39
 testRunner.Then("the book name should be \"WHY CAN’T WE FALL ASLEEP?\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
