//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AKCWPF.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AKCWPF.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!--
        ///// (c) Copyright Microsoft Corporation.
        ///// This source is subject to Microsoft Public License (Ms-PL).
        ///// Please see http://go.microsoft.com/fwlink/?LinkID=131993 for details.
        ///// All other rights reserved.
        ///--&gt;
        ///
        ///&lt;ResourceDictionary
        ///  xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot;
        ///  xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;
        ///  xmlns:mc=&quot;http://schemas.openxmlformats.org/markup-compatibility/2006&quot;
        ///  mc:Ignorable=&quot;d&quot;
        ///  xmlns:d=&quot;http://schemas.microsoft.com/express [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BureauBlue {
            get {
                return ResourceManager.GetString("BureauBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!--
        ///// (c) Copyright Microsoft Corporation.
        ///// This source is subject to Microsoft Public License (Ms-PL).
        ///// Please see http://go.microsoft.com/fwlink/?LinkID=131993 for details.
        ///// All other rights reserved.
        ///--&gt;
        ///
        ///&lt;ResourceDictionary
        ///    xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot;
        ///    xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;
        ///    xmlns:mc=&quot;http://schemas.openxmlformats.org/markup-compatibility/2006&quot;
        ///    xmlns:basic=&quot;clr-namespace:Microsoft.Windows.Controls;ass [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TwilightBlue {
            get {
                return ResourceManager.GetString("TwilightBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ResourceDictionary xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot;
        ///    xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;
        ///	xmlns:d=&quot;http://schemas.microsoft.com/expression/blend/2008&quot; 
        ///	xmlns:mc=&quot;http://schemas.openxmlformats.org/markup-compatibility/2006&quot; 
        ///	xmlns:vsm=&quot;clr-namespace:System.Windows;assembly=WPFToolkit&quot;
        ///	mc:Ignorable=&quot;d&quot;&gt;
        ///
        ///    &lt;SolidColorBrush x:Key=&quot;WindowBackgroundBrush&quot; Color=&quot;#FF333333&quot; /&gt;
        ///    &lt;SolidColorBrush x:Key=&quot;BaseColorBrush&quot; Color=&quot;#FF9FD752&quot;/&gt;
        ///     [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UXMusingsGreen {
            get {
                return ResourceManager.GetString("UXMusingsGreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!--
        ///// (c) Copyright Microsoft Corporation.
        ///// This source is subject to Microsoft Public License (Ms-PL).
        ///// Please see http://go.microsoft.com/fwlink/?LinkID=131993 for details.
        ///// All other rights reserved.
        ///--&gt;
        ///
        ///&lt;ResourceDictionary
        ///  xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot;
        ///  xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;
        ///  xmlns:mc=&quot;http://schemas.openxmlformats.org/markup-compatibility/2006&quot;
        ///  mc:Ignorable=&quot;d&quot;
        ///  xmlns:d=&quot;http://schemas.microsoft.com/express [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WhistlerBlue {
            get {
                return ResourceManager.GetString("WhistlerBlue", resourceCulture);
            }
        }
    }
}
